export const CART_SAVE_REQUEST = 'CART_SAVE_REQUEST';
export const CART_SAVE_SUCCESS = 'CART_SAVE_SUCCESS';
export const CART_SAVE_FAILURE = 'CART_SAVE_FAILURE';

export const FETCH_USER_CART_REQUEST = 'FETCH_USER_CART_REQUEST';
export const FETCH_USER_CART_SUCCESS = 'FETCH_USER_CART_SUCCESS';
export const FETCH_USER_CART_FAILURE = 'FETCH_USER_CART_FAILURE';

export const DELETE_PRODUCT_FROM_CART_REQUEST = 'DELETE_PRODUCT_FROM_CART';
export const DELETE_PRODUCT_FROM_CART_SUCCESS = 'DELETE_PRODUCT_FROM_CART_SUCCESS';
export const DELETE_PRODUCT_FROM_CART_FAILURE = 'DELETE_PRODUCT_FROM_CART_FAILURE';