export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE'

export const USER_ORDER_HISTORY_REQUEST = 'USER_ORDER_HISTORY_REQUEST'
export const USER_ORDER_HISTORY_SUCCESS = 'USER_ORDER_HISTORY_SUCCESS'
export const USER_ORDER_HISTORY_FAILURE = 'USER_ORDER_HISTORY_FAILURE'

export const ORDER_HISTORY_ALL_USERS_REQUEST = 'ORDER_HISTORY_ALL_USERS_REQUEST'
export const ORDER_HISTORY_ALL_USERS_SUCCESS = 'ORDER_HISTORY_ALL_USERS_SUCCESS'
export const ORDER_HISTORY_ALL_USERS_FAILURE = 'ORDER_HISTORY_ALL_USERS_FAILURE'

export const CHANGE_ORDER_STATUS_REQUEST = 'CHANGE_ORDER_STATUS_REQUEST'
export const CHANGE_ORDER_STATUS_SUCCESS = 'CHANGE_ORDER_STATUS_SUCCESS'
export const CHANGE_ORDER_STATUS_FAILURE = 'CHANGE_ORDER_STATUS_FAILURE'
